# Generated by Django 3.2 on 2023-09-14 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_auto_20220520_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='license_status',
            field=models.CharField(choices=[('invalid', 'invalid'), ('valid', 'valid'), ('expired', 'expired')], default='valid', max_length=10),
        ),
    ]
