# Generated by Django 3.2 on 2023-09-16 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_license_license_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_status', models.CharField(choices=[('invalid', 'invalid'), ('valid', 'valid'), ('expired', 'expired')], default='valid', max_length=10)),
                ('created_datetime', models.DateTimeField(auto_now=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licenses.license')),
            ],
        ),
    ]
