# Generated by Django 3.2 on 2023-09-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0004_licenselog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_status',
            field=models.IntegerField(choices=[('invalid', 'invalid'), ('valid', 'valid'), ('expired', 'expired')], default='valid', max_length=10),
        ),
        migrations.AlterField(
            model_name='license',
            name='license_type',
            field=models.IntegerField(choices=[('production', 0), ('evaluation', 1)]),
        ),
        migrations.AlterField(
            model_name='license',
            name='package',
            field=models.IntegerField(choices=[('javascript_sdk', 0), ('ios_sdk', 1), ('android_sdk', 2)]),
        ),
    ]
