# Generated by Django 3.2 on 2023-09-16 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0005_auto_20230916_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_status',
            field=models.IntegerField(choices=[('invalid', 0), ('valid', 1), ('expired', 2)], default=1),
        ),
        migrations.AlterField(
            model_name='licenselog',
            name='license_status',
            field=models.CharField(choices=[('invalid', 0), ('valid', 1), ('expired', 2)], default=1, max_length=10),
        ),
    ]
