# Generated by Django 3.2 on 2023-09-17 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0006_auto_20230916_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenselog',
            name='license_status',
        ),
    ]
