# Generated by Django 3.2 on 2023-09-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0007_remove_licenselog_license_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120)),
                ('sender', models.CharField(max_length=120)),
                ('recipient', models.CharField(max_length=120)),
                ('sent_datetime', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
            ],
        ),
    ]
